package:
  name: diamond
  version: "0.7.10"

source:
  git_url: https://github.com/bbuchfink/diamond.git
  git_tag: v0.7.10
  patches:
    - cmake_patch

build:
  number: 1

requirements:
  build:
    - cmake
    - boost >=1.53.0
  run:
    - boost >=1.53.0

test:
  commands:
    - diamond -h

about:
  summary: a BLAST-compatible local aligner for mapping protein and translated DNA query sequences against a protein reference database
  home: http://github.com/bbuchfink/diamond
  license: Modified BSD License
  license_file: src/COPYING
