package:
  name: seppgg
  version: "0.1"

source:
  - url: https://raw.github.com/smirarab/sepp-refs/master/gg/sepp-package.tar.bz
    md5: 7d5f181a01862aba5108b12e916871f6
  - path: ./reloc.patch
  - path: ./expected_result.tre
  - path: ./tiny_fragments.mfa
  - path: ./tiny_reference.aln
  - path: ./tiny_reference.newick

build:
  number: 1
  #~ binary_has_prefix_files:
    #~ - share/seppgg/main.config

requirements:
  run:
    - python >=3
    - biom-format
  build:
    - python >=3
    - biom-format

test:
  files:
  commands:
    - pwd
    - seppgg $PREFIX/share/seppgg/tiny_fragments.mfa t1 -t $PREFIX/share/seppgg/tiny_reference.newick -a $PREFIX/share/seppgg/tiny_reference.aln -x 1
    #~ - diff expected_result.tre t1_placement.tog.relabelled.tre

about:
  summary: Insert Deblur fragments into GreenGenes phylogeny.
  home: https://github.com/smirarab/sepp/blob/master/sepp-package/README.md
